### ISSUE TITLE
One dictionary 

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/frontend-bokeh#1]
def get_freq():
    return ['a', 'q', 'm', 'd']

def get_freq_descriptions():
    return ['Annual', 'Quarterly', 'Monthly', 'Daily']

**Comment by zarak** [comment]
A regular dictionary will not work because order may not be preserved. That's why I had proposed a list of tuples, which can also be indexed by integers from 0 to n-1 for the nth element. But perhaps you prefer the `OrderedDict` in 641d319.

**Comment by epogrebnyak** [comment]
@zarak : the OrderDict you put in code does not guarantee order, because you created it based on regular dictionary. See e75a5b9425f4688a60d5f8ba43e2579a25b8e96a for various fixes. Changing the ```get_freq()``` a little bit also helps later to clean out code in ```update_plot()```. I deleted some extra bevaiviours there too.
